#!/usr/bin/python3
import numpy as np
import matplotlib.pyplot as plt
input_data = pd.read_csv('main.csv')
from sklearn.preprocessing import LabelEncoder
input_data['Class_N']=labelencoder.fit_transform(input_data['Class'])
input_data['Class']=input_data['Class'].astype('category')
print(input_data.dtypes)
input_data['Class']=input_data['Class'].cat.codes
print(input_data)
plt.figure()
plt.hist(df, bins=5)
plt.xlabel('Class')
plt.title('Class Values')
plt.show()
